version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.8
    steps:
      - checkout
      - run: mvn clean install -DskipTests

  test:
    docker:
      - image: cimg/openjdk:17.0.8

    steps:
      - checkout
      - run: mvn test

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
        command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - docker/build:
         image: jaxtoh/education-space
         tag: <<pipeline.git.tag>>
      - docker/push:
         image: jaxtoh/education-space
         tag: <<pipeline.git.tag>>

  scan:
    docker:
      - image: cimg/openjdk:17.0.8
    environment:
      IMAGE_NAME: jaxtoh/education-space:v1.0.0
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
          severity-threshold: medium

  deploy:
    docker:
      - image: cimg/openjdk:17.0.8

    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a jaxtoh-simple-crm
            heroku container:release web -a jaxtoh-simple-crm

workflows:
  ci-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop
      - scan:
          requires:
            - build

  cicd-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - test:
          requires:
            - build
          filters:
            branches:
              only: release
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: release
      - scan:
          requires:
            - build
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: release